### PR TITLE
Drkwint/sacred

### PR DESCRIPTION
**Pull request by DrKwint**
Adds testing and early stopping

### CODE REVIEW

**Comment by jakew42** [comment]
Change "test" terminology to "validation" since it is used for early stopping, rather than final testing.

**Comment by jakew42** [comment]
Train and validate are printing the exact same numbers:

EPOCH 18
TRAIN
Final Accuracy: 0.516486
Weak Classifier Accuracies: [ 0.56868988  0.4263221   0.36352164  0.34727564  0.32972756  0.32504007
  0.2956931   0.28814101  0.27207533  0.26682693]
validate
Final Accuracy: 0.516486
Weak Classifier Accuracies: [ 0.56868988  0.4263221   0.36352164  0.34727564  0.32972756  0.32504007
  0.2956931   0.28814101  0.27207533  0.26682693]


Also, printing Loss per epoch would be helpful

**Comment by jakew42** [comment]
Ran into this error using progressive training:

ERROR - boosted_experiment - Failed after 0:00:09!
Traceback (most recent calls WITHOUT Sacred internals):
  File "./SelfBoostingNetworks/run_boosted_experiment.py", line 91, in run
    load_stem=load_stem)
  File "/lustre/work/samal/jakew42/SelfBoosting/SelfBoostingNetworks/train_boosted.py", line 105, in run
    stem=load_stem)
  File "/lustre/work/samal/jakew42/SelfBoosting/SelfBoostingNetworks/util.py", line 165, in train
    stem_saver.restore(session, stem)
  File "/home/samal/jakew42/.conda/envs/cenv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1775, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/samal/jakew42/.conda/envs/cenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/samal/jakew42/.conda/envs/cenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    '. Try explicitly setting the type of the feed tensor'
TypeError: Type of feed value True with type <class 'bool'> is not compatible with Tensor type <class 'object'>. Try explicitly setting the type of the feed tensor to a larger type (e.g. int64).

**Comment by DrKwint** [comment]
I've fixed the loading of stem networks here, e.g., `python run_boosted_experiment.py with "load_stem='BigConvStem'"`

**Comment by jakew42** [comment]
Merge approved.

**Pull request merged**
